//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStokUpdate.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class TBLMUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUSTERILER()
        {
            this.TBLSATISLAR = new HashSet<TBLSATISLAR>();
        }

        public int MUSTERIID { get; set; }
        [MinLength(4)]
        [Required(ErrorMessage = "Zorunlu alan!")]
        public string MUSTERIAD { get; set; }

        [Required(ErrorMessage = "Zorunlu alan!")]
        public string MUSTERISOYAD { get; set; }


        [Required(ErrorMessage = "Zorunlu alan!")]
        [DataType(DataType.EmailAddress)]
        [MaxLength(50)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "E-mail formunda giriþ yapýnýz!")]
        public string MUSTERIMAIL { get; set; }
        [Required(ErrorMessage = "Zorunlu alan!")]
        public string MUSTERISIFRE { get; set; }

        [Required(ErrorMessage = "Zorunlu alan!")]
        [System.ComponentModel.DataAnnotations.Compare("MUSTERISIFRE", ErrorMessage = "Bir önceki þifre ile uyuþmuyor!")]
        public string CONFIRMPASSWORD { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISLAR> TBLSATISLAR { get; set; }
    }
}
